[.text-justify]
== Domain Analysis and Modeling (30 pages)

[quote,Alberto Brandolini]
The amount of energy necessary to refute bullshit is an order of magnitude bigger than to produce it.

As we saw in the previous chapter, misinterpreted requirements cause a significant portion of software projects to fail. Arriving at a shared understanding and creating a useful domain model, necessitates high degrees of collaboration with domain experts. In this chapter, we will introduce the sample application we will use throughout the book and explore modeling techniques such as domain storytelling and event storming to enhance our collective understanding of the problem in a reliable and structured manner.

Originally conceived by Alberto Brandolini, EventStorming has emerged as a flexible and convenient format for the collaborative exploration of complex domains. In this chapter, we will introduce the sample application used throughout the book and use the different flavors of EventStorming to arrive at a shared understanding of the problem and brainstorm ideas to arrive at a solution.

=== Introducing the LC Application
In many countries, international trade represents a significant portion of the gross domestic product (GDP) -- making an exchange of capital, goods, and services between untrusted parties spread across the globe a necessity. While economic organizations such as the World Trade Organization (WTO) were formed specifically to ease and facilitate this process, differences in factors such as economic policy, trade laws, currency, etc. ensure that carrying out trade internationally remains a complex process even today.

==== Documentary Letters of Credit
Documentary Letters of Credit(LC) is a financial instrument issued by the Banks as a contract between the Buyer(or Importer) and the Seller(or Exporter).  This contract specifies terms and conditions of the transaction under which buyer promises to pay the exporter in exchange for the goods or services provided by the seller.  Letters of Credit transaction typically involves multiple parties besides the buyer and the seller.

1. Bank that buyer has relationship with, with whom he requests for issuing the LC application, called the "Issuing Bank".
2. Bank that advises the LC to the seller in their country, referred as the "Advising Bank".
3. Bank that seller has relationship with, with whom he provides documents for the shipment of goods, or the services provided, referred as the "Negotiating Bank".
4. Agency that handles shipment of goods, the "Freight Forwarder".
5. It is very common to find that Issuing Bank in Exporter's country do not have any business relationship with the Negotiating Bank in the Importer's country.  In such cases, they involve a common Bank that both of them have relationship with, referred as "Reimbursement Bank".

==== Issuing Bank LC Application

=== Narrowing Down Scope

=== Introducing Domain Events

=== Identifying Hot Spots, Puzzlers and Blockers

=== Commands and User Intentions/Actions/Decisions

=== Extracting Personas, Users and Actors

=== Read/Query Models and Data Needed To Make Decisions

=== Grouping Commands and Events into Aggregates
