[.text-justify]
== Domain Analysis and Modeling (30 pages)

[quote,Alberto Brandolini]
The amount of energy necessary to refute bullshit is an order of magnitude bigger than to produce it.

As we saw in the previous chapter, misinterpreted requirements cause a significant portion of software projects to fail. Arriving at a shared understanding and creating a useful domain model, necessitates high degrees of collaboration with domain experts. In this chapter, we will introduce the sample application we will use throughout the book and explore modeling techniques such as domain storytelling and event storming to enhance our collective understanding of the problem in a reliable and structured manner.

Originally conceived by Alberto Brandolini, EventStorming has emerged as a flexible and convenient format for the collaborative exploration of complex domains. In this chapter, we will introduce the sample application used throughout the book and use the different flavors of EventStorming to arrive at a shared understanding of the problem and brainstorm ideas to arrive at a solution.

=== Introducing the LC Application
In many countries, international trade represents a significant portion of the gross domestic product (GDP) -- making an exchange of capital, goods, and services between untrusted parties spread across the globe a necessity. While economic organizations such as the World Trade Organization (WTO) were formed specifically to ease and facilitate this process, differences in factors such as economic policy, trade laws, currency, etc. ensure that carrying out trade internationally can be a complex process with several entities involved across countries. Letters of Credit exist to simplify this process. Let's take a look at how they work.

==== What is Letter of Credit (LCs)?
Documentary Letter of Credit (LC) is a financial instrument issued by the banks as a contract between the importer (or buyer) and the exporter (or seller). This contract specifies terms and conditions of the transaction under which importer promises to pay the exporter in exchange for the goods or services provided by the exporter.  Letters of Credit transaction typically involves multiple parties. A simplified summary of the parties involved is described below:

1. *Importer*: The buyer of the goods or services.
2. *Exporter*: The seller of the goods or services.
3. *Freight Forwarder*: The agency that handles shipment of goods on behalf of the exporter. This is only applicable in cases there is an exchange of physical goods.
4. *Issuing Bank*: The bank that the importer requests to issue the LC application. Usually the importer has a pre-existing relationship with this bank.
5. *Advising Bank*: The bank that informs the exporter about the issuance of the LC. This is usually a bank that is native to the exporter's country.
6. *Negotiating Bank*: The bank that the exporter submits documents for the shipment of goods, or the services provided. Usually the exporter has a pre-existing relationship with this bank.
7. *Reimbursement Bank*: The bank that reimburses the funds to the negotiating bank, at the request of the issuing bank.

NOTE: It is important to note that the same bank can play more than one role for a given transaction. In the most complex cases, there can be four distinct banks involved for a transaction (sometimes even more, but we will skip those cases for brevity).

==== The Issuing Bank LC Application
XYZ Bank has reached out to us in order to automate the process of LC application and issuance. In this chapter, and indeed the rest of this book, we will strive to understand, evolve, design and build a software solution to automate this process.

=== Enhancing Shared Understanding
When working with a problem where domain concepts are unclear, there is a need to arrive at a common understanding among key team members (both those that have bright ideas -- business/product people, and those that translate those ideas into working software -- software developers). For this process to be effective, we will ideally find means that are:

* Quick, informal and effective
* Easy to learn and retain for both non-technical and technical team members
* Pictorial - because a picture can be worth a thousand words
* Usable for both coarse grained and fine grained scenarios

There are several means to arrive at this shared understanding. Some of the commonly used approaches are listed below:

* UML
* BPMN
* Use Cases
* User Story Mapping
* CRC Models
* Data Flow Diagrams
* TDD, BDD, FDD, ATDD


=== Domain Storytelling

[quote,Alberto Brandolini]
It’s developers’ (mis)understanding, not expert knowledge that gets released in production.

=== Event Storming

==== Introducing Domain Events

==== Identifying Hot Spots, Puzzlers and Blockers

==== Commands and User Intentions/Actions/Decisions

==== Extracting Personas, Users and Actors

=== Read/Query Models and Data Needed To Make Decisions

=== Grouping Commands and Events into Aggregates
