== Implementing the User Interface -- Task-based (20 pages)
[quote, Marty Rubin]
To accomplish a difficult task, one must first make it easy.

The essence of DDD is a lot about capturing the business process and user intent a lot more closely. Task-based UIs (in contrast to CRUD-based UIs) treat user intents as first class citizens and perpetrate the spirit of DDD's ubiquitous language very elegantly. In this chapter, we will design the UI for the LC application using the https://openjfx.com/[JavaFX]footnote:[https://openjfx.com/] framework. We will also employ https://martinfowler.com/articles/consumerDrivenContracts.html[consumer-driven contracts]footnote:[https://martinfowler.com/articles/consumerDrivenContracts.html] using https://docs.pact.io/[Pact JVM]footnote:[https://docs.pact.io/] to express expectations of the user interface to the service implementation.

=== Technical Requirements

=== Bootstrapping the UI

=== MVC vs. MVP vs. MVVM

=== Task-based vs. CRUD-based UIs

=== Invoking commands

=== Implementing the Submit LC Screen

