name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Graphviz and Custom Fonts
        run: |
          sudo apt-get install graphviz
          cd /usr/share/fonts
          wget "https://github.com/google/fonts/raw/main/ofl/gloriahallelujah/GloriaHallelujah.ttf"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache local repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and package with Maven
        run: >-
          mvn -B clean package --file pom.xml
      - name: Publish Chapters
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_FOR_CHAPTER_GITHUB_PAGES }}
        with:
          source-directory: 'book/target/generated-docs'
          destination-github-username: 'ddd-book-java'
          destination-repository-name: 'chapters'
          user-email: me@karthiks.in
          target-branch: main